// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a session-mode connection (advisory locks, DDL) —
    // DATABASE_URL is transaction-pooled for the app's runtime queries.
    url: process.env["DIRECT_URL"],
  },
});
