import type { Config } from "tailwindcss";

// Design tokens ported verbatim from the Stitch (stitch.withgoogle.com) exports
// in stitch-export/ — all 9 screens shared this exact token set.
export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d6e3ff",
        "on-primary": "#ffffff",
        danger: "#EF4444",
        "secondary-fixed": "#ffdcc1",
        "surface-bright": "#f8f9fd",
        "on-primary-fixed": "#011b3e",
        "surface-container-lowest": "#ffffff",
        secondary: "#8f4e00",
        "on-primary-container": "#778cb5",
        "tertiary-fixed-dim": "#f6ba8e",
        "on-error-container": "#93000a",
        "on-surface": "#191c1f",
        "outline-variant": "#c4c6cf",
        "surface-container-high": "#e7e8ec",
        "on-tertiary-fixed": "#2f1400",
        "surface-glass": "rgba(255, 255, 255, 0.7)",
        "on-background": "#191c1f",
        "on-tertiary-container": "#b48059",
        primary: "#000f27",
        "on-surface-variant": "#44474e",
        "tertiary-fixed": "#ffdcc4",
        "primary-fixed-dim": "#b1c7f3",
        "on-secondary-fixed": "#2e1500",
        tertiary: "#1d0a00",
        "text-primary": "#1B1B1B",
        error: "#ba1a1a",
        "surface-container": "#edeef2",
        "surface-dim": "#d9dade",
        warning: "#F59E0B",
        "on-tertiary-fixed-variant": "#663d1b",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e2e6",
        background: "#f8f9fd",
        "primary-container": "#0b2447",
        "secondary-container": "#fd9830",
        "surface-container-highest": "#e1e2e6",
        "surface-tint": "#4a5f85",
        "on-secondary-container": "#683700",
        "inverse-primary": "#b1c7f3",
        "inverse-surface": "#2e3134",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3f7",
        "secondary-fixed-dim": "#ffb77a",
        success: "#22C55E",
        "tertiary-container": "#3c1c00",
        "on-secondary-fixed-variant": "#6c3a00",
        outline: "#74777f",
        surface: "#f8f9fd",
        "text-secondary": "#6B7280",
        "inverse-on-surface": "#eff1f5",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#32476c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      // NOTE: our custom spacing scale reuses the names "xs/sm/md/lg/xl",
      // which collide with Tailwind's built-in max-w-{xs,sm,md,lg,xl}
      // utilities under this Tailwind v4 + legacy @config setup — max-w-sm
      // resolves to our 12px spacing token, not the standard 24rem. This
      // maxWidth override does not reliably win against that collision, so
      // avoid max-w-{xs,sm,md,lg,xl} entirely; use an arbitrary value like
      // max-w-[24rem] instead wherever a prose-width container is needed.
      spacing: {
        xs: "4px",
        md: "24px",
        sm: "12px",
        "margin-desktop": "32px",
        lg: "40px",
        "margin-mobile": "16px",
        xl: "64px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        serif: ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
} satisfies Config;
